// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/clone-enhance.tsx, not this copy.
'use client'

import { useEffect } from 'react'

/**
 * The entire client-side runtime of an FFC static clone.
 *
 * A captured WordPress site arrives carrying ~1.9 MB of jQuery, jQuery Migrate,
 * Underscore, the Divi theme bundle, Divi Plus, Swiper, Hustle, MediaElement, a
 * cookie-consent plugin and two analytics beacons. Measured against the DOM
 * actually captured for this site, that payload exists to serve exactly two
 * behaviours: a hamburger menu and a scroll-in fade. Everything else Divi ships
 * a handler for — toggles, accordions, tabs, sliders, video overlays, counters,
 * countdowns, lightboxes, contact forms — appears on zero pages.
 *
 * It is a client component rather than a `<script>` in the captured markup for
 * a reason that only shows up in one direction: the fragment is injected with
 * `dangerouslySetInnerHTML`, and a `<script>` arriving that way runs on a cold
 * load (static export writes it into the HTML the browser parses) and silently
 * does not run on a client-side navigation. A behaviour present or absent
 * depending on how the visitor arrived is worse than either.
 *
 * Three properties are deliberate and worth keeping if this is ever edited:
 *
 *   - **No JavaScript is required to read the site.** The capture strips Divi's
 *     `.et-waypoint{opacity:0}` rule, so content is painted whether or not this
 *     runs. Animation is enhancement; visibility never is.
 *   - **Nothing is built from a string.** No innerHTML, no eval, no injected
 *     script. The mobile menu is a `cloneNode()` of markup the server already
 *     sent, which is why no page text can become markup here.
 *   - **Nothing leaves the page.** No fetch, no beacon, no third-party host.
 */

/** Modules that can own a hamburger: the Divi menu module and its fullwidth twin. */
const MENU_MODULE = '.et_pb_menu, .et_pb_fullwidth_menu'

type Teardown = () => void

/**
 * Wire one menu module's hamburger.
 *
 * Divi ships the toggle as a bare `<span>` and builds the mobile list in
 * JavaScript. Both are reproduced, with the accessibility defects fixed rather
 * than reproduced: the span becomes a real button to the accessibility tree, it
 * carries its expanded state, and it answers Enter and Space.
 */
function wireMenu(module: Element): Teardown | null {
  const bar = module.querySelector<HTMLElement>('.mobile_menu_bar')
  const nav = module.querySelector<HTMLElement>('.mobile_nav')
  const source = module.querySelector<HTMLElement>(
    '.et_pb_menu__menu ul.et-menu, .et-menu-nav ul.et-menu'
  )
  if (!bar || !nav || !source) return null

  // Built once, on first open. A menu nobody opens costs nothing.
  let list: HTMLElement | null = null
  let open = false

  bar.setAttribute('role', 'button')
  bar.setAttribute('tabindex', '0')
  bar.setAttribute('aria-label', 'Toggle menu')
  bar.setAttribute('aria-expanded', 'false')

  const build = (): HTMLElement => {
    if (list) return list
    // cloneNode, not innerHTML: the markup is copied as a parsed tree, so there
    // is no string for anything to be injected into.
    list = source.cloneNode(true) as HTMLElement
    list.removeAttribute('id')
    list.className = 'et_mobile_menu'
    // The clone carries the desktop menu's ids; a duplicate id is invalid and
    // breaks in-page anchors and label targeting.
    list.querySelectorAll('[id]').forEach((el) => el.removeAttribute('id'))
    list.style.display = 'none'
    nav.appendChild(list)
    return list
  }

  const setOpen = (next: boolean) => {
    const el = build()
    open = next
    el.style.display = next ? 'block' : 'none'
    bar.setAttribute('aria-expanded', next ? 'true' : 'false')
    nav.classList.toggle('opened', next)
    nav.classList.toggle('closed', !next)
  }

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!open)
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
    event.preventDefault()
    setOpen(!open)
  }
  // Escape closes, and focus goes back to the control that opened it —
  // otherwise a keyboard user is stranded inside a list they cannot dismiss.
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!open) return
    setOpen(false)
    bar.focus()
  }

  bar.addEventListener('click', onClick)
  bar.addEventListener('keydown', onKeyDown)
  module.addEventListener('keydown', onEscape as EventListener)

  return () => {
    bar.removeEventListener('click', onClick)
    bar.removeEventListener('keydown', onKeyDown)
    module.removeEventListener('keydown', onEscape as EventListener)
  }
}

/**
 * The Jupiter / MK theme's hamburger, which is a different theme entirely.
 *
 * Everything above is Divi. newheightseducation.org is Jupiter, and on a
 * Jupiter capture none of the Divi selectors match -- so wiring this component
 * up made no difference at all until this function existed. Measured at 390px
 * on /who-we-are/ and /contact-us/: two hamburger controls present, **zero**
 * visible navigation links, and tapping either changed nothing. A visitor on a
 * phone could not move around the site.
 *
 * Jupiter needs almost nothing from us, because the capture already carries
 * both halves:
 *
 *   `div.mk-nav-responsive-link`  the control (38x38, top right)
 *   `div.mk-responsive-wrap`      the panel, holding `ul.mk-responsive-nav`
 *                                 with all 45 menu links
 *
 * and the theme's own stylesheet already says `.mk-responsive-wrap {
 * display: none }`. So this toggles that one property and the theme styles the
 * open menu itself. Nothing is built, nothing is cloned, no markup is authored
 * here -- which keeps the "nothing is built from a string" property above, by
 * not needing a string in the first place.
 *
 * The accessibility defects are fixed rather than reproduced, exactly as
 * `wireMenu` does for Divi: the bare `<div>` becomes a real button to the
 * accessibility tree, carries its expanded state, and answers Enter, Space and
 * Escape.
 */
const MK_TOGGLE = '.mk-nav-responsive-link'

function wireMkMenu(toggle: Element): Teardown | null {
  const scope: ParentNode = toggle.closest('header') ?? document
  const panel = scope.querySelector<HTMLElement>('.mk-responsive-wrap')
  if (!panel || !(toggle instanceof HTMLElement)) return null
  // A panel with no links is not a menu; leave it alone rather than offering a
  // control that opens an empty box.
  if (!panel.querySelector('a')) return null

  // State is READ FROM THE PANEL, never held in a local flag, and every toggle
  // sharing that panel is updated together.
  //
  // A header can carry more than one `.mk-nav-responsive-link` -- this capture
  // carries two, one per breakpoint -- and `wireMkMenu` runs once per toggle,
  // each resolving the SAME panel through `closest('header')`. With a
  // per-toggle `open` flag the second control starts out believing the menu is
  // closed: after the first opens it, tapping the second writes
  // `display: block` over an already-open panel, so it does not close and the
  // visitor's tap does nothing. That is the dead-control shape this whole file
  // exists to remove, reintroduced by the fix for it. `aria-expanded` on the
  // untouched toggle was wrong for the same reason.
  //
  // `getComputedStyle` and not `panel.style.display`: before the first toggle
  // the inline style is empty and the truth lives in the theme's own
  // stylesheet rule.
  const isOpen = () => getComputedStyle(panel).display !== 'none'
  const peers = () => Array.from(scope.querySelectorAll<HTMLElement>(MK_TOGGLE))

  toggle.setAttribute('role', 'button')
  toggle.setAttribute('tabindex', '0')
  toggle.setAttribute('aria-label', 'Toggle menu')
  toggle.setAttribute('aria-expanded', isOpen() ? 'true' : 'false')

  const setOpen = (next: boolean) => {
    // The theme's rule is `display: none`; overriding the property it sets is
    // the whole mechanism. `block` and not `''` because `''` would fall back
    // to that rule and the menu would never appear.
    panel.style.display = next ? 'block' : 'none'
    for (const peer of peers()) peer.setAttribute('aria-expanded', next ? 'true' : 'false')
  }

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!isOpen())
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
    event.preventDefault()
    setOpen(!isOpen())
  }
  // Escape must return focus to a control the visitor can actually reach, and
  // `toggle` is not reliably that one. `wireMkMenu` runs per toggle, so a
  // header with one control per breakpoint registers this handler once per
  // control; the first to see the keydown closes the panel and every later one
  // returns at the `isOpen()` guard. Focus therefore always went to whichever
  // control happened to be wired FIRST -- and at any given width only one of
  // them is rendered, so that is a coin flip. `focus()` on a `display: none`
  // element silently does nothing, which leaves Escape closing the menu and
  // stranding the keyboard visitor wherever they were: the dead-control shape
  // this file exists to remove, in the handler written to prevent it.
  //
  // jsdom lays nothing out, so `renderedPeers()` is empty there and the
  // fallback keeps the single-toggle behaviour the other tests assert.
  const renderedPeers = () =>
    peers().filter(
      (el) => el.offsetWidth > 0 || el.offsetHeight > 0 || el.getClientRects().length > 0
    )
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!isOpen()) return
    setOpen(false)
    ;(renderedPeers()[0] ?? toggle).focus()
  }

  toggle.addEventListener('click', onClick)
  toggle.addEventListener('keydown', onKeyDown)
  document.addEventListener('keydown', onEscape as EventListener)

  // The submenu chevrons inside the panel. Jupiter draws a `<span>` carrying
  // an SVG arrow next to every parent item and hides `ul.sub-menu` with
  // `display: none`; without a handler the chevron is a control that promises
  // a submenu and does nothing -- the same dead-control shape this migration
  // has already had to clear elsewhere. Measured before this: tapping one left
  // the visible link count at 13.
  //
  // Nothing is destroyed if a capture has no submenus: the loop simply finds
  // no arrows.
  const subTeardowns: Teardown[] = []
  for (const arrow of panel.querySelectorAll<HTMLElement>('.mk-nav-arrow')) {
    const sub = arrow.parentElement?.querySelector<HTMLElement>(':scope > ul.sub-menu')
    if (!sub) continue
    let subOpen = false
    arrow.setAttribute('role', 'button')
    arrow.setAttribute('tabindex', '0')
    arrow.setAttribute('aria-expanded', 'false')
    const label = arrow.parentElement?.querySelector('a')?.textContent?.trim()
    arrow.setAttribute('aria-label', label ? `Toggle ${label} submenu` : 'Toggle submenu')
    const setSub = (next: boolean) => {
      subOpen = next
      sub.style.display = next ? 'block' : 'none'
      arrow.setAttribute('aria-expanded', next ? 'true' : 'false')
      // The theme's own state classes, so its chevron rotates as it would have.
      arrow.classList.toggle('mk-nav-sub-opened', next)
      arrow.classList.toggle('mk-nav-sub-closed', !next)
    }
    const onSubClick = (event: Event) => {
      event.preventDefault()
      event.stopPropagation()
      setSub(!subOpen)
    }
    const onSubKey = (event: KeyboardEvent) => {
      if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
      event.preventDefault()
      setSub(!subOpen)
    }
    arrow.addEventListener('click', onSubClick)
    arrow.addEventListener('keydown', onSubKey)
    subTeardowns.push(() => {
      arrow.removeEventListener('click', onSubClick)
      arrow.removeEventListener('keydown', onSubKey)
    })
  }

  return () => {
    toggle.removeEventListener('click', onClick)
    toggle.removeEventListener('keydown', onKeyDown)
    document.removeEventListener('keydown', onEscape as EventListener)
    subTeardowns.forEach((off) => off())
  }
}

/**
 * The WordPress core navigation block's overlay menu, the third theme family
 * this file has had to learn.
 *
 * Everything above is Divi or Jupiter. tamkeensports.org is a block theme
 * (Twenty Twenty-Five), and on a block-theme capture none of those selectors
 * match -- so, as with Jupiter before it, wiring this component made no
 * difference until this function existed. The capture carries the whole
 * overlay: the hamburger `<button>`, the `#modal-1` container, the close
 * `<button>` and every link. It also carries the core stylesheet's open-state
 * rules (`.is-menu-open` displays the overlay; below 600px the container is
 * hidden and the hamburger shown). What it does NOT carry is the Interactivity
 * API runtime that core drives those rules from: the `data-wp-on--click` /
 * `data-wp-class--is-menu-open` directives survive as inert attributes, so on
 * a phone the hamburger is a dead control and the site has no navigation.
 *
 * The same minimal shape as `wireMkMenu`: nothing is built or cloned, the
 * state classes core would have toggled are toggled, and the stylesheet does
 * the rest. The ARIA core binds at runtime (`role="dialog"`, `aria-modal`,
 * `aria-label` on the dialog element; `aria-expanded` on the hamburger) is
 * set here instead, so the open overlay is announced as the modal it is and
 * removed again on close so the inline desktop menu is not. Open moves focus
 * into the overlay, as core's `focusFirstElement` did; close and Escape return
 * it to the hamburger.
 *
 * Core also closes the overlay on `focusout`, so a visitor tabbing past the
 * last link lands back on the page. That is NOT reproduced: with
 * `html.has-modal-open { overflow: hidden }` the page behind the overlay
 * cannot scroll, so losing focus from it is the one dead-end this handler
 * would add rather than remove. Escape and the close button are the exits.
 */
const BLOCK_NAV_OPEN = '.wp-block-navigation__responsive-container-open'

function wireBlockNavigation(opener: Element): Teardown | null {
  if (!(opener instanceof HTMLElement)) return null
  // Core resolves the container by `aria-controls` when the block carries it,
  // and by adjacency otherwise; this capture has no `aria-controls`, so the
  // container is the next sibling, with a scoped query as the fallback.
  const scope: ParentNode = opener.closest('.wp-block-navigation') ?? document
  const sibling = opener.nextElementSibling
  const container =
    sibling instanceof HTMLElement &&
    sibling.classList.contains('wp-block-navigation__responsive-container')
      ? sibling
      : scope.querySelector<HTMLElement>('.wp-block-navigation__responsive-container')
  if (!container) return null
  // A container with no links is not a menu; leave it alone rather than
  // offering a control that opens an empty overlay.
  if (!container.querySelector('a')) return null
  const closer = container.querySelector<HTMLElement>(
    '.wp-block-navigation__responsive-container-close'
  )
  const dialog = container.querySelector<HTMLElement>('.wp-block-navigation__responsive-dialog')

  // State is READ FROM THE CONTAINER, as `wireMkMenu` reads its panel, so a
  // second control sharing the container (core renders none, but the rule is
  // cheap) can never disagree with the first.
  const isOpen = () => container.classList.contains('is-menu-open')

  opener.setAttribute('aria-expanded', isOpen() ? 'true' : 'false')

  const setOpen = (next: boolean) => {
    // The three classes core's `data-wp-class--*` directives would have
    // written: `is-menu-open` is the one the overlay rules key on,
    // `has-modal-open` on the container styles the close bar, and on `<html>`
    // it locks the page scroll behind the overlay.
    container.classList.toggle('is-menu-open', next)
    container.classList.toggle('has-modal-open', next)
    document.documentElement.classList.toggle('has-modal-open', next)
    opener.setAttribute('aria-expanded', next ? 'true' : 'false')
    if (dialog) {
      if (next) {
        dialog.setAttribute('role', 'dialog')
        dialog.setAttribute('aria-modal', 'true')
        dialog.setAttribute('aria-label', 'Menu')
      } else {
        dialog.removeAttribute('role')
        dialog.removeAttribute('aria-modal')
        dialog.removeAttribute('aria-label')
      }
    }
  }

  const open = () => {
    setOpen(true)
    // Into the overlay, as core's `focusFirstElement` did. The container is
    // `tabindex="-1"` in the capture, so it can take focus and the next Tab
    // lands on the close button, then the first link.
    container.focus()
  }
  const close = () => {
    setOpen(false)
    opener.focus()
  }

  const onOpenClick = (event: Event) => {
    event.preventDefault()
    if (isOpen()) close()
    else open()
  }
  const onCloseClick = (event: Event) => {
    event.preventDefault()
    close()
  }
  // Escape anywhere in the document while the overlay is open: the overlay
  // covers the page, so wherever focus is, the visitor is inside it.
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!isOpen()) return
    close()
  }

  opener.addEventListener('click', onOpenClick)
  closer?.addEventListener('click', onCloseClick)
  document.addEventListener('keydown', onEscape as EventListener)

  return () => {
    opener.removeEventListener('click', onOpenClick)
    closer?.removeEventListener('click', onCloseClick)
    document.removeEventListener('keydown', onEscape as EventListener)
    // A component unmounting mid-open must not leave the page scroll locked.
    if (isOpen()) setOpen(false)
  }
}

/**
 * The core navigation block's submenu toggles (the chevron next to "Events").
 *
 * Core's stylesheet shows a submenu in three ways: on hover, via
 * `:focus-within` for a block set to open on hover only, and via the toggle
 * button -- `.wp-block-navigation-submenu__toggle[aria-expanded=true] ~
 * .wp-block-navigation__submenu-container`. This block is `open-on-hover-click`,
 * which core excludes from the `:focus-within` rule on purpose: the button is
 * the keyboard path. The Interactivity API runtime set `aria-expanded` on it,
 * and the capture strips that runtime, so measured on the converted site a
 * Tab stop landed on "Events submenu", Enter did nothing, and a keyboard
 * visitor had no way to reach Chicago or Dallas from the menu. Hover and the
 * mobile overlay (where the submenu is always expanded) were unaffected.
 *
 * Setting the attribute is the whole fix; the stylesheet does the rest.
 * Escape closes the submenu and returns focus to the toggle, and focus
 * leaving the item closes it, as core did.
 */
const BLOCK_SUBMENU_TOGGLE = '.wp-block-navigation-submenu__toggle'

function wireBlockSubmenu(toggle: Element): Teardown | null {
  if (!(toggle instanceof HTMLElement)) return null
  const item = toggle.closest<HTMLElement>('.wp-block-navigation-submenu, .has-child')
  const container = item?.querySelector<HTMLElement>('.wp-block-navigation__submenu-container')
  if (!item || !container || !container.querySelector('a')) return null

  const isOpen = () => toggle.getAttribute('aria-expanded') === 'true'
  const setOpen = (next: boolean) => toggle.setAttribute('aria-expanded', next ? 'true' : 'false')
  setOpen(false)

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!isOpen())
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!isOpen()) return
    setOpen(false)
    toggle.focus()
  }
  // Closes when focus moves outside the item, so a keyboard visitor tabbing
  // past the last submenu link does not leave it hanging open. `relatedTarget`
  // is null when focus leaves the document; that closes it too.
  const onFocusOut = (event: FocusEvent) => {
    const next = event.relatedTarget
    if (next instanceof Node && item.contains(next)) return
    setOpen(false)
  }

  toggle.addEventListener('click', onClick)
  item.addEventListener('keydown', onKeyDown as EventListener)
  item.addEventListener('focusout', onFocusOut as EventListener)
  return () => {
    toggle.removeEventListener('click', onClick)
    item.removeEventListener('keydown', onKeyDown as EventListener)
    item.removeEventListener('focusout', onFocusOut as EventListener)
  }
}

/**
 * Reveal Divi's scroll-in elements.
 *
 * Divi hides `.et-waypoint` at `opacity: 0` and reveals it from a scroll
 * handler. The capture removes that hiding rule, so this only adds the class
 * that starts the keyframe animation the stylesheet already defines. If
 * IntersectionObserver is missing, every element is revealed immediately — the
 * failure mode is "no animation", never "no content".
 */
function wireWaypoints(): Teardown | null {
  const targets = document.querySelectorAll<HTMLElement>('.et-waypoint:not(.et-animated)')
  if (!targets.length) return null

  if (typeof window.IntersectionObserver !== 'function') {
    targets.forEach((el) => el.classList.add('et-animated'))
    return null
  }

  const observer = new window.IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (!entry.isIntersecting) continue
        entry.target.classList.add('et-animated')
        observer.unobserve(entry.target)
      }
    },
    { rootMargin: '0px 0px -10% 0px' }
  )
  targets.forEach((el) => observer.observe(el))
  return () => observer.disconnect()
}

export default function CloneEnhance() {
  useEffect(() => {
    const teardowns: Teardown[] = []
    document.querySelectorAll(MENU_MODULE).forEach((module) => {
      const off = wireMenu(module)
      if (off) teardowns.push(off)
    })
    // Jupiter/MK captures match none of the Divi selectors above. Both are
    // attempted because one repo's converter output can be either theme, and a
    // selector that matches nothing costs nothing.
    document.querySelectorAll(MK_TOGGLE).forEach((toggle) => {
      const off = wireMkMenu(toggle)
      if (off) teardowns.push(off)
    })
    // Block themes (core navigation block) match neither of the above.
    document.querySelectorAll(BLOCK_NAV_OPEN).forEach((opener) => {
      const off = wireBlockNavigation(opener)
      if (off) teardowns.push(off)
    })
    document.querySelectorAll(BLOCK_SUBMENU_TOGGLE).forEach((toggle) => {
      const off = wireBlockSubmenu(toggle)
      if (off) teardowns.push(off)
    })
    const offWaypoints = wireWaypoints()
    if (offWaypoints) teardowns.push(offWaypoints)
    return () => teardowns.forEach((off) => off())
  }, [])

  return null
}
