// Generated by workflow 706 (convert-clone-to-routes.mjs). Edit the template in
// FFC-Cloudflare-Automation/assets/clone-enhance.tsx, not this copy.
'use client'

import { useEffect } from 'react'

/**
 * The entire client-side runtime of an FFC static clone.
 *
 * A captured WordPress site arrives carrying ~1.9 MB of jQuery, jQuery Migrate,
 * Underscore, the Divi theme bundle, Divi Plus, Swiper, Hustle, MediaElement, a
 * cookie-consent plugin and two analytics beacons. Measured against the DOM
 * actually captured for this site, that payload exists to serve exactly two
 * behaviours: a hamburger menu and a scroll-in fade. Everything else Divi ships
 * a handler for — toggles, accordions, tabs, sliders, video overlays, counters,
 * countdowns, lightboxes, contact forms — appears on zero pages.
 *
 * It is a client component rather than a `<script>` in the captured markup for
 * a reason that only shows up in one direction: the fragment is injected with
 * `dangerouslySetInnerHTML`, and a `<script>` arriving that way runs on a cold
 * load (static export writes it into the HTML the browser parses) and silently
 * does not run on a client-side navigation. A behaviour present or absent
 * depending on how the visitor arrived is worse than either.
 *
 * Three properties are deliberate and worth keeping if this is ever edited:
 *
 *   - **No JavaScript is required to read the site.** The capture strips Divi's
 *     `.et-waypoint{opacity:0}` rule, so content is painted whether or not this
 *     runs. Animation is enhancement; visibility never is.
 *   - **Nothing is built from a string.** No innerHTML, no eval, no injected
 *     script. The mobile menu is a `cloneNode()` of markup the server already
 *     sent, which is why no page text can become markup here.
 *   - **Nothing leaves the page.** No fetch, no beacon, no third-party host.
 */

/** Modules that can own a hamburger: the Divi menu module and its fullwidth twin. */
const MENU_MODULE = '.et_pb_menu, .et_pb_fullwidth_menu'

type Teardown = () => void

/**
 * Wire one menu module's hamburger.
 *
 * Divi ships the toggle as a bare `<span>` and builds the mobile list in
 * JavaScript. Both are reproduced, with the accessibility defects fixed rather
 * than reproduced: the span becomes a real button to the accessibility tree, it
 * carries its expanded state, and it answers Enter and Space.
 */
function wireMenu(module: Element): Teardown | null {
  const bar = module.querySelector<HTMLElement>('.mobile_menu_bar')
  const nav = module.querySelector<HTMLElement>('.mobile_nav')
  const source = module.querySelector<HTMLElement>(
    '.et_pb_menu__menu ul.et-menu, .et-menu-nav ul.et-menu'
  )
  if (!bar || !nav || !source) return null

  // Built once, on first open. A menu nobody opens costs nothing.
  let list: HTMLElement | null = null
  let open = false

  bar.setAttribute('role', 'button')
  bar.setAttribute('tabindex', '0')
  bar.setAttribute('aria-label', 'Toggle menu')
  bar.setAttribute('aria-expanded', 'false')

  const build = (): HTMLElement => {
    if (list) return list
    // cloneNode, not innerHTML: the markup is copied as a parsed tree, so there
    // is no string for anything to be injected into.
    list = source.cloneNode(true) as HTMLElement
    list.removeAttribute('id')
    list.className = 'et_mobile_menu'
    // The clone carries the desktop menu's ids; a duplicate id is invalid and
    // breaks in-page anchors and label targeting.
    list.querySelectorAll('[id]').forEach((el) => el.removeAttribute('id'))
    list.style.display = 'none'
    nav.appendChild(list)
    return list
  }

  const setOpen = (next: boolean) => {
    const el = build()
    open = next
    el.style.display = next ? 'block' : 'none'
    bar.setAttribute('aria-expanded', next ? 'true' : 'false')
    nav.classList.toggle('opened', next)
    nav.classList.toggle('closed', !next)
  }

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!open)
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
    event.preventDefault()
    setOpen(!open)
  }
  // Escape closes, and focus goes back to the control that opened it —
  // otherwise a keyboard user is stranded inside a list they cannot dismiss.
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!open) return
    setOpen(false)
    bar.focus()
  }

  bar.addEventListener('click', onClick)
  bar.addEventListener('keydown', onKeyDown)
  module.addEventListener('keydown', onEscape as EventListener)

  return () => {
    bar.removeEventListener('click', onClick)
    bar.removeEventListener('keydown', onKeyDown)
    module.removeEventListener('keydown', onEscape as EventListener)
  }
}

/**
 * The Jupiter / MK theme's hamburger, which is a different theme entirely.
 *
 * Everything above is Divi. newheightseducation.org is Jupiter, and on a
 * Jupiter capture none of the Divi selectors match -- so wiring this component
 * up made no difference at all until this function existed. Measured at 390px
 * on /who-we-are/ and /contact-us/: two hamburger controls present, **zero**
 * visible navigation links, and tapping either changed nothing. A visitor on a
 * phone could not move around the site.
 *
 * Jupiter needs almost nothing from us, because the capture already carries
 * both halves:
 *
 *   `div.mk-nav-responsive-link`  the control (38x38, top right)
 *   `div.mk-responsive-wrap`      the panel, holding `ul.mk-responsive-nav`
 *                                 with all 45 menu links
 *
 * and the theme's own stylesheet already says `.mk-responsive-wrap {
 * display: none }`. So this toggles that one property and the theme styles the
 * open menu itself. Nothing is built, nothing is cloned, no markup is authored
 * here -- which keeps the "nothing is built from a string" property above, by
 * not needing a string in the first place.
 *
 * The accessibility defects are fixed rather than reproduced, exactly as
 * `wireMenu` does for Divi: the bare `<div>` becomes a real button to the
 * accessibility tree, carries its expanded state, and answers Enter, Space and
 * Escape.
 */
const MK_TOGGLE = '.mk-nav-responsive-link'

function wireMkMenu(toggle: Element): Teardown | null {
  const scope: ParentNode = toggle.closest('header') ?? document
  const panel = scope.querySelector<HTMLElement>('.mk-responsive-wrap')
  if (!panel || !(toggle instanceof HTMLElement)) return null
  // A panel with no links is not a menu; leave it alone rather than offering a
  // control that opens an empty box.
  if (!panel.querySelector('a')) return null

  // State is READ FROM THE PANEL, never held in a local flag, and every toggle
  // sharing that panel is updated together.
  //
  // A header can carry more than one `.mk-nav-responsive-link` -- this capture
  // carries two, one per breakpoint -- and `wireMkMenu` runs once per toggle,
  // each resolving the SAME panel through `closest('header')`. With a
  // per-toggle `open` flag the second control starts out believing the menu is
  // closed: after the first opens it, tapping the second writes
  // `display: block` over an already-open panel, so it does not close and the
  // visitor's tap does nothing. That is the dead-control shape this whole file
  // exists to remove, reintroduced by the fix for it. `aria-expanded` on the
  // untouched toggle was wrong for the same reason.
  //
  // `getComputedStyle` and not `panel.style.display`: before the first toggle
  // the inline style is empty and the truth lives in the theme's own
  // stylesheet rule.
  const isOpen = () => getComputedStyle(panel).display !== 'none'
  const peers = () => Array.from(scope.querySelectorAll<HTMLElement>(MK_TOGGLE))

  toggle.setAttribute('role', 'button')
  toggle.setAttribute('tabindex', '0')
  toggle.setAttribute('aria-label', 'Toggle menu')
  toggle.setAttribute('aria-expanded', isOpen() ? 'true' : 'false')

  const setOpen = (next: boolean) => {
    // The theme's rule is `display: none`; overriding the property it sets is
    // the whole mechanism. `block` and not `''` because `''` would fall back
    // to that rule and the menu would never appear.
    panel.style.display = next ? 'block' : 'none'
    for (const peer of peers()) peer.setAttribute('aria-expanded', next ? 'true' : 'false')
  }

  const onClick = (event: Event) => {
    event.preventDefault()
    setOpen(!isOpen())
  }
  const onKeyDown = (event: KeyboardEvent) => {
    if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
    event.preventDefault()
    setOpen(!isOpen())
  }
  // Escape must return focus to a control the visitor can actually reach, and
  // `toggle` is not reliably that one. `wireMkMenu` runs per toggle, so a
  // header with one control per breakpoint registers this handler once per
  // control; the first to see the keydown closes the panel and every later one
  // returns at the `isOpen()` guard. Focus therefore always went to whichever
  // control happened to be wired FIRST -- and at any given width only one of
  // them is rendered, so that is a coin flip. `focus()` on a `display: none`
  // element silently does nothing, which leaves Escape closing the menu and
  // stranding the keyboard visitor wherever they were: the dead-control shape
  // this file exists to remove, in the handler written to prevent it.
  //
  // jsdom lays nothing out, so `renderedPeers()` is empty there and the
  // fallback keeps the single-toggle behaviour the other tests assert.
  const renderedPeers = () =>
    peers().filter(
      (el) => el.offsetWidth > 0 || el.offsetHeight > 0 || el.getClientRects().length > 0
    )
  const onEscape = (event: KeyboardEvent) => {
    if (event.key !== 'Escape' && event.key !== 'Esc') return
    if (!isOpen()) return
    setOpen(false)
    ;(renderedPeers()[0] ?? toggle).focus()
  }

  toggle.addEventListener('click', onClick)
  toggle.addEventListener('keydown', onKeyDown)
  document.addEventListener('keydown', onEscape as EventListener)

  // The submenu chevrons inside the panel. Jupiter draws a `<span>` carrying
  // an SVG arrow next to every parent item and hides `ul.sub-menu` with
  // `display: none`; without a handler the chevron is a control that promises
  // a submenu and does nothing -- the same dead-control shape this migration
  // has already had to clear elsewhere. Measured before this: tapping one left
  // the visible link count at 13.
  //
  // Nothing is destroyed if a capture has no submenus: the loop simply finds
  // no arrows.
  const subTeardowns: Teardown[] = []
  for (const arrow of panel.querySelectorAll<HTMLElement>('.mk-nav-arrow')) {
    const sub = arrow.parentElement?.querySelector<HTMLElement>(':scope > ul.sub-menu')
    if (!sub) continue
    let subOpen = false
    arrow.setAttribute('role', 'button')
    arrow.setAttribute('tabindex', '0')
    arrow.setAttribute('aria-expanded', 'false')
    const label = arrow.parentElement?.querySelector('a')?.textContent?.trim()
    arrow.setAttribute('aria-label', label ? `Toggle ${label} submenu` : 'Toggle submenu')
    const setSub = (next: boolean) => {
      subOpen = next
      sub.style.display = next ? 'block' : 'none'
      arrow.setAttribute('aria-expanded', next ? 'true' : 'false')
      // The theme's own state classes, so its chevron rotates as it would have.
      arrow.classList.toggle('mk-nav-sub-opened', next)
      arrow.classList.toggle('mk-nav-sub-closed', !next)
    }
    const onSubClick = (event: Event) => {
      event.preventDefault()
      event.stopPropagation()
      setSub(!subOpen)
    }
    const onSubKey = (event: KeyboardEvent) => {
      if (event.key !== 'Enter' && event.key !== ' ' && event.key !== 'Spacebar') return
      event.preventDefault()
      setSub(!subOpen)
    }
    arrow.addEventListener('click', onSubClick)
    arrow.addEventListener('keydown', onSubKey)
    subTeardowns.push(() => {
      arrow.removeEventListener('click', onSubClick)
      arrow.removeEventListener('keydown', onSubKey)
    })
  }

  return () => {
    toggle.removeEventListener('click', onClick)
    toggle.removeEventListener('keydown', onKeyDown)
    document.removeEventListener('keydown', onEscape as EventListener)
    subTeardowns.forEach((off) => off())
  }
}

/**
 * Reveal Divi's scroll-in elements.
 *
 * Divi hides `.et-waypoint` at `opacity: 0` and reveals it from a scroll
 * handler. The capture removes that hiding rule, so this only adds the class
 * that starts the keyframe animation the stylesheet already defines. If
 * IntersectionObserver is missing, every element is revealed immediately — the
 * failure mode is "no animation", never "no content".
 */
function wireWaypoints(): Teardown | null {
  const targets = document.querySelectorAll<HTMLElement>('.et-waypoint:not(.et-animated)')
  if (!targets.length) return null

  if (typeof window.IntersectionObserver !== 'function') {
    targets.forEach((el) => el.classList.add('et-animated'))
    return null
  }

  const observer = new window.IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (!entry.isIntersecting) continue
        entry.target.classList.add('et-animated')
        observer.unobserve(entry.target)
      }
    },
    { rootMargin: '0px 0px -10% 0px' }
  )
  targets.forEach((el) => observer.observe(el))
  return () => observer.disconnect()
}

export default function CloneEnhance() {
  useEffect(() => {
    const teardowns: Teardown[] = []
    document.querySelectorAll(MENU_MODULE).forEach((module) => {
      const off = wireMenu(module)
      if (off) teardowns.push(off)
    })
    // Jupiter/MK captures match none of the Divi selectors above. Both are
    // attempted because one repo's converter output can be either theme, and a
    // selector that matches nothing costs nothing.
    document.querySelectorAll(MK_TOGGLE).forEach((toggle) => {
      const off = wireMkMenu(toggle)
      if (off) teardowns.push(off)
    })
    const offWaypoints = wireWaypoints()
    if (offWaypoints) teardowns.push(offWaypoints)
    return () => teardowns.forEach((off) => off())
  }, [])

  return null
}
