import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'League - Tamkeen Sports' },
  description:
    'SUMMER SPORTS LEAGUE We’re excited to explore interest for a summer volleyball or basketball league! All games will take place on completely private indoor c...',
  openGraph: {
    title: 'League - Tamkeen Sports',
    description:
      'SUMMER SPORTS LEAGUE We’re excited to explore interest for a summer volleyball or basketball league! All games will take place on completely private indoor c...',
    url: '/league/',
    type: 'article',
  },
  twitter: {
    title: 'League - Tamkeen Sports',
    description:
      'SUMMER SPORTS LEAGUE We’re excited to explore interest for a summer volleyball or basketball league! All games will take place on completely private indoor c...',
  },
  alternates: { canonical: '/league/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-401 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('league') }}
    />
  )
}
