import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Uncategorized - Tamkeen Sports' },
  description:
    'Tamkeen Sports Home Contact About Us Donate CHI Events Join Our Team Refund Policy Chicago Calendar League DFW Events DFW Calendar No posts found! © 2026…',
  openGraph: {
    title: 'Uncategorized - Tamkeen Sports',
    description:
      'Tamkeen Sports Home Contact About Us Donate CHI Events Join Our Team Refund Policy Chicago Calendar League DFW Events DFW Calendar No posts found! © 2026…',
    url: '/category/uncategorized/',
    type: 'article',
  },
  twitter: {
    title: 'Uncategorized - Tamkeen Sports',
    description:
      'Tamkeen Sports Home Contact About Us Donate CHI Events Join Our Team Refund Policy Chicago Calendar League DFW Events DFW Calendar No posts found! © 2026…',
  },
  alternates: { canonical: '/category/uncategorized/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone archive category category-uncategorized category-1 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('category/uncategorized') }}
    />
  )
}
