import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'About Us',
    description:
      'ABOUT US MISSION Tamkeen Sports was founded in March 2025 to create private, women-only sports events where women can stay active, build community, and compe...',
    path: '/about/',
  }),
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-37 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('about') }}
    />
  )
}
