import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'CHI Events - Tamkeen Sports' },
  description:
    'UPCOMING EVENTS Pilates & Reflections (Reformer Edition) Tamkeen Sports x Noor PilatesDate: October 4, 2026Time: 10:00-10:50 AM ∨ 11:00–11:50 AMLocation:...',
  openGraph: {
    title: 'CHI Events - Tamkeen Sports',
    description:
      'UPCOMING EVENTS Pilates & Reflections (Reformer Edition) Tamkeen Sports x Noor PilatesDate: October 4, 2026Time: 10:00-10:50 AM ∨ 11:00–11:50 AMLocation:...',
    url: '/events/',
    type: 'article',
  },
  twitter: {
    title: 'CHI Events - Tamkeen Sports',
    description:
      'UPCOMING EVENTS Pilates & Reflections (Reformer Edition) Tamkeen Sports x Noor PilatesDate: October 4, 2026Time: 10:00-10:50 AM ∨ 11:00–11:50 AMLocation:...',
  },
  alternates: { canonical: '/events/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-109 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('events') }}
    />
  )
}
