import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
// `pageMetadata` resolves the canonical through siteUrl(), so it carries the
// GitHub Pages base path; a relative canonical here lost it. The title is the
// captured one without its site-name suffix, which the title template adds.
export const metadata: Metadata = pageMetadata({
  title: 'CHI Events',
  description:
    'UPCOMING EVENTS Pilates & Reflections (Reformer Edition) Tamkeen Sports x Noor PilatesDate: October 4, 2026Time: 10:00-10:50 AM ∨ 11:00–11:50 AMLocation:...',
  path: '/events/',
})

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-109 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('events') }}
    />
  )
}
