import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'Contact',
    description:
      'CONTACT US We’d love to hear from you! Fill out the form below, and we’ll get back to you as soon as possible.',
    path: '/contact/',
  }),
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-36 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('contact') }}
    />
  )
}
