import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Tamkeen Sports' },
  description:
    '​Tamkeen Sports is a nonprofit organization dedicated to creating women-only sports events for Muslim women and girls. We provide a welcoming space where wom...',
  openGraph: {
    title: 'Tamkeen Sports',
    description:
      '​Tamkeen Sports is a nonprofit organization dedicated to creating women-only sports events for Muslim women and girls. We provide a welcoming space where wom...',
    url: '/',
    type: 'article',
  },
  twitter: {
    title: 'Tamkeen Sports',
    description:
      '​Tamkeen Sports is a nonprofit organization dedicated to creating women-only sports events for Muslim women and girls. We provide a welcoming space where wom...',
  },
  alternates: { canonical: '/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-35 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
