import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'
import { siteConfig } from '@/lib/site.config'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
const base = pageMetadata({
  title: siteConfig.name,
  description:
    'Tamkeen Sports is a nonprofit organization dedicated to creating women-only sports events for Muslim women and girls. We provide a welcoming space where wom...',
  path: '/',
})

export const metadata: Metadata = {
  ...base,
  title: { absolute: siteConfig.name },
  openGraph: { ...base.openGraph, title: siteConfig.name },
  twitter: { ...base.twitter, title: siteConfig.name },
}

export default function Page() {
  return (
    <div
      className="ffc-clone home wp-singular page-template-default page page-id-35 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('index') }}
    />
  )
}
