import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Join Our Team - Tamkeen Sports' },
  description:
    'JOIN OUR TEAM We would greatly appreciate your help! Fill out the application below, and we’ll get back to you as soon as possible.',
  openGraph: {
    title: 'Join Our Team - Tamkeen Sports',
    description:
      'JOIN OUR TEAM We would greatly appreciate your help! Fill out the application below, and we’ll get back to you as soon as possible.',
    url: '/join/',
    type: 'article',
  },
  twitter: {
    title: 'Join Our Team - Tamkeen Sports',
    description:
      'JOIN OUR TEAM We would greatly appreciate your help! Fill out the application below, and we’ll get back to you as soon as possible.',
  },
  alternates: { canonical: '/join/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-209 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('join') }}
    />
  )
}
