import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  ...pageMetadata({
    title: 'DFW Events',
    description:
      'DFW UPCOMING EVENTS REFINE: Striving for Excellence Tamkeen Sports DFW x Eagle Martial ArtsDate: October 18, 2026Time: 12:30-3:00 PMLocation: Eagle Martial A...',
    path: '/dfw-events/',
  }),
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-443 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('dfw-events') }}
    />
  )
}
