import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'DFW Events - Tamkeen Sports' },
  description:
    'DFW UPCOMING EVENTS Dodgeball Tournament Tamkeen Sports DFW x The Sweet SpellDate: October 4, 2026Time: 2:45-3:45 PMLocation: Wisdom360 Multi-Sports GymWomen...',
  openGraph: {
    title: 'DFW Events - Tamkeen Sports',
    description:
      'DFW UPCOMING EVENTS Dodgeball Tournament Tamkeen Sports DFW x The Sweet SpellDate: October 4, 2026Time: 2:45-3:45 PMLocation: Wisdom360 Multi-Sports GymWomen...',
    url: '/dfw-events/',
    type: 'article',
  },
  twitter: {
    title: 'DFW Events - Tamkeen Sports',
    description:
      'DFW UPCOMING EVENTS Dodgeball Tournament Tamkeen Sports DFW x The Sweet SpellDate: October 4, 2026Time: 2:45-3:45 PMLocation: Wisdom360 Multi-Sports GymWomen...',
  },
  alternates: { canonical: '/dfw-events/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-443 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('dfw-events') }}
    />
  )
}
