import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
// `pageMetadata` resolves the canonical through siteUrl(), so it carries the
// GitHub Pages base path; a relative canonical here lost it. The title is the
// captured one without its site-name suffix, which the title template adds.
export const metadata: Metadata = pageMetadata({
  title: 'DFW Events',
  description:
    'DFW UPCOMING EVENTS Dodgeball Tournament Tamkeen Sports DFW x The Sweet SpellDate: October 4, 2026Time: 2:45-3:45 PMLocation: Wisdom360 Multi-Sports GymWomen...',
  path: '/dfw-events/',
})

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-443 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('dfw-events') }}
    />
  )
}
