import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'DFW Calendar - Tamkeen Sports' },
  description: 'DFW EVENTS CALENDAR',
  openGraph: {
    title: 'DFW Calendar - Tamkeen Sports',
    description: 'DFW EVENTS CALENDAR',
    url: '/dfw-calendar/',
    type: 'article',
  },
  twitter: {
    title: 'DFW Calendar - Tamkeen Sports',
    description: 'DFW EVENTS CALENDAR',
  },
  alternates: { canonical: '/dfw-calendar/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-446 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('dfw-calendar') }}
    />
  )
}
