import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'
import { pageMetadata } from '@/lib/pageMetadata'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
// `pageMetadata` resolves the canonical through siteUrl(), so it carries the
// GitHub Pages base path; a relative canonical here lost it. The title is the
// captured one without its site-name suffix, which the title template adds.
export const metadata: Metadata = pageMetadata({
  title: 'Donate',
  description:
    'SUPPORT US Your donation helps Tamkeen Sports create safe, empowering spaces for women and girls to play sports, build community, and support meaningful caus...',
  path: '/donate/',
})

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-81 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('donate') }}
    />
  )
}
