import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Donate - Tamkeen Sports' },
  description:
    'SUPPORT US Your donation helps Tamkeen Sports create safe, empowering spaces for women and girls to play sports, build community, and support meaningful caus...',
  openGraph: {
    title: 'Donate - Tamkeen Sports',
    description:
      'SUPPORT US Your donation helps Tamkeen Sports create safe, empowering spaces for women and girls to play sports, build community, and support meaningful caus...',
    url: '/donate/',
    type: 'article',
  },
  twitter: {
    title: 'Donate - Tamkeen Sports',
    description:
      'SUPPORT US Your donation helps Tamkeen Sports create safe, empowering spaces for women and girls to play sports, build community, and support meaningful caus...',
  },
  alternates: { canonical: '/donate/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-81 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('donate') }}
    />
  )
}
