import type { Metadata } from 'next'
import { loadCloneContent } from '@/lib/clone-content'

// Generated by workflow 706 from the live site capture. Edit the source site,
// or the converter in FFC-Cloudflare-Automation, rather than this file.
export const metadata: Metadata = {
  title: { absolute: 'Refund Policy - Tamkeen Sports' },
  description:
    'REFUND POLICY All event ticket sales and registration fees for Tamkeen Sports are final and non-refundable.We understand that unexpected situations can arise...',
  openGraph: {
    title: 'Refund Policy - Tamkeen Sports',
    description:
      'REFUND POLICY All event ticket sales and registration fees for Tamkeen Sports are final and non-refundable.We understand that unexpected situations can arise...',
    url: '/refund-policy/',
    type: 'article',
  },
  twitter: {
    title: 'Refund Policy - Tamkeen Sports',
    description:
      'REFUND POLICY All event ticket sales and registration fees for Tamkeen Sports are final and non-refundable.We understand that unexpected situations can arise...',
  },
  alternates: { canonical: '/refund-policy/' },
}

export default function Page() {
  return (
    <div
      className="ffc-clone wp-singular page-template-default page page-id-215 wp-custom-logo wp-embed-responsive wp-theme-twentytwentyfive theme-twentytwentyfive woocommerce-uses-block-theme woocommerce-block-theme-has-button-styles woocommerce-no-js pagelayer-body"
      dangerouslySetInnerHTML={{ __html: loadCloneContent('refund-policy') }}
    />
  )
}
